### PR TITLE
Implement xpc_copy_entitlements_for_pid()

### PR DESCRIPTION
**Pull request by wjk**
Does mostly what the title says. Note that I have not tested this code on a PureDarwin VM image.

### CODE REVIEW

**Comment by csekel** [comment]
@wjk please build and test that this code still allows the PureDarwin Vm to boot.

**Comment by wjk** [comment]
@csekel Tested on the PureDarwin VM. It successfully boots to shell. However, the `xpc_entitlements_test` binary fails with an `EINVAL` errno when run in the VM; it does not fail when run on the macOS kernel. More investigation will be required.

**Comment by csekel** [comment]
Okay awesome, wonder if it has to do with us not having rootless or a security framework at the moment? Maybe we get part of the Security Framework built?

**Comment by wjk** [comment]
@csekel I've done some digging, and the results are not good. XNU by itself cannot parse code-signing metadata; it merely passes on what is given to it by a kext. There are three kexts that are involved in parsing this data, all of them proprietary: `AppleMobileFileIntegrity.kext`, `CoreTrust.kext`, and `corecrypto.kext`.

From what I can tell, corecrypto contains the low-level cryptographic primitives used to validate the signatures. CoreTrust contains the public-key blobs corresponding to the various certificates that macOS knows about. And AppleMobileFileIntegrity does the yea-or-nay decision on whether to run a process, and passes the code signing data (including entitlements) back to the kernel.

We are going to have to rewrite all three of these if we want code signing to work on PureDarwin. However, I don't think this is a _complete_ deal-breaker that keeps us from merging this PR.

**Comment by csekel** [comment]
@sjc can you please look at this when you get a chance?

**Comment by sjc** [comment]
@csekel Looks fine to me, Cliff. It can be merged whenever you like, as long as @wjk has finished adding to it.

**Comment by wjk** [comment]
@csekel I'm done adding to this PR. It can be merged at your convenience. If anything else needs doing, I'll create a new PR. Thanks!

**Pull request merged**
