### PR TITLE
Clean up repository

### PR DESCRIPTION
**Pull request by wjk**

### CODE REVIEW

**Comment by wjk** [comment]
I'm going to be replacing the contents of the entire repo in a new PR, so this PR is now obsolete. (I tried hard to do a proper, manual merge, but it was just too difficult.)

**Comment by wjk** [comment]
After further discussion with the team, this PR is now relevant again, as I am no longer going to blow away the entire repo. Reopening.

**Comment by sjc** [comment]
Could you mark this with something like `WIP:` until you're ready for us to review and merge? Thanks.

**Comment by wjk** [comment]
@sjc This one is ready for review. I am sending in all functional changes in a second PR.

**Pull request merged**
